export type PaymentMethod = "Efectivo" | "Tarjeta" | "Yape";
export type EntryType = "Servicio" | "Producto" | "Gasto";

export interface Transaction {
  id: string;
  hora: string;
  tipo: EntryType;
  descripcion: string;
  empleado: string;
  pago: PaymentMethod;
  monto: number;
}

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    hora: "08:05",
    tipo: "Servicio",
    descripcion: "Corte de cabello",
    empleado: "Carlos",
    pago: "Efectivo",
    monto: 25,
  },
  {
    id: "2",
    hora: "08:30",
    tipo: "Servicio",
    descripcion: "Tinte completo",
    empleado: "María",
    pago: "Tarjeta",
    monto: 120,
  },
  {
    id: "3",
    hora: "08:55",
    tipo: "Producto",
    descripcion: "Shampoo Kerastase",
    empleado: "Ana",
    pago: "Yape",
    monto: 45,
  },
  {
    id: "4",
    hora: "09:10",
    tipo: "Servicio",
    descripcion: "Barba y bigote",
    empleado: "Carlos",
    pago: "Efectivo",
    monto: 15,
  },
  {
    id: "5",
    hora: "09:30",
    tipo: "Gasto",
    descripcion: "Compra de insumos",
    empleado: "Admin",
    pago: "Efectivo",
    monto: 80,
  },
  {
    id: "6",
    hora: "09:50",
    tipo: "Servicio",
    descripcion: "Corte + lavado",
    empleado: "María",
    pago: "Yape",
    monto: 35,
  },
  {
    id: "7",
    hora: "10:00",
    tipo: "Producto",
    descripcion: "Cera para cabello",
    empleado: "Ana",
    pago: "Efectivo",
    monto: 22,
  },
  {
    id: "8",
    hora: "10:20",
    tipo: "Servicio",
    descripcion: "Peinado para evento",
    empleado: "María",
    pago: "Tarjeta",
    monto: 60,
  },
  {
    id: "9",
    hora: "10:45",
    tipo: "Servicio",
    descripcion: "Alisado brasileño",
    empleado: "Ana",
    pago: "Tarjeta",
    monto: 180,
  },
  {
    id: "10",
    hora: "11:00",
    tipo: "Producto",
    descripcion: "Acondicionador Wella",
    empleado: "Carlos",
    pago: "Yape",
    monto: 38,
  },
  {
    id: "11",
    hora: "11:20",
    tipo: "Servicio",
    descripcion: "Corte infantil",
    empleado: "Carlos",
    pago: "Efectivo",
    monto: 18,
  },
  {
    id: "12",
    hora: "11:40",
    tipo: "Gasto",
    descripcion: "Pago de luz",
    empleado: "Admin",
    pago: "Tarjeta",
    monto: 150,
  },
  {
    id: "13",
    hora: "12:00",
    tipo: "Servicio",
    descripcion: "Coloración parcial",
    empleado: "María",
    pago: "Yape",
    monto: 75,
  },
  {
    id: "14",
    hora: "12:30",
    tipo: "Producto",
    descripcion: "Mascarilla capilar",
    empleado: "Ana",
    pago: "Efectivo",
    monto: 30,
  },
  {
    id: "15",
    hora: "13:00",
    tipo: "Servicio",
    descripcion: "Depilación de cejas",
    empleado: "Ana",
    pago: "Efectivo",
    monto: 12,
  },
  {
    id: "16",
    hora: "13:20",
    tipo: "Servicio",
    descripcion: "Corte + barba",
    empleado: "Carlos",
    pago: "Tarjeta",
    monto: 30,
  },
  {
    id: "17",
    hora: "13:45",
    tipo: "Producto",
    descripcion: "Gel fijador",
    empleado: "Carlos",
    pago: "Yape",
    monto: 15,
  },
  {
    id: "18",
    hora: "14:00",
    tipo: "Servicio",
    descripcion: "Hidratación capilar",
    empleado: "María",
    pago: "Tarjeta",
    monto: 55,
  },
  {
    id: "19",
    hora: "14:30",
    tipo: "Gasto",
    descripcion: "Reparación de sillón",
    empleado: "Admin",
    pago: "Efectivo",
    monto: 200,
  },
  {
    id: "20",
    hora: "15:00",
    tipo: "Servicio",
    descripcion: "Mechas californianas",
    empleado: "Ana",
    pago: "Tarjeta",
    monto: 140,
  },
  {
    id: "21",
    hora: "15:20",
    tipo: "Producto",
    descripcion: "Tónico anticaída",
    empleado: "María",
    pago: "Efectivo",
    monto: 50,
  },
  {
    id: "22",
    hora: "15:40",
    tipo: "Servicio",
    descripcion: "Corte de cabello",
    empleado: "Carlos",
    pago: "Yape",
    monto: 25,
  },
  {
    id: "23",
    hora: "16:00",
    tipo: "Servicio",
    descripcion: "Alaciado permanente",
    empleado: "María",
    pago: "Tarjeta",
    monto: 160,
  },
  {
    id: "24",
    hora: "16:30",
    tipo: "Producto",
    descripcion: "Spray fijador Redken",
    empleado: "Ana",
    pago: "Yape",
    monto: 42,
  },
  {
    id: "25",
    hora: "16:50",
    tipo: "Servicio",
    descripcion: "Tratamiento con keratina",
    empleado: "Ana",
    pago: "Tarjeta",
    monto: 200,
  },
  {
    id: "26",
    hora: "17:10",
    tipo: "Gasto",
    descripcion: "Útiles de limpieza",
    empleado: "Admin",
    pago: "Efectivo",
    monto: 35,
  },
  {
    id: "27",
    hora: "17:30",
    tipo: "Servicio",
    descripcion: "Corte + lavado + secado",
    empleado: "María",
    pago: "Efectivo",
    monto: 45,
  },
  {
    id: "28",
    hora: "17:50",
    tipo: "Producto",
    descripcion: "Crema para peinar",
    empleado: "Carlos",
    pago: "Yape",
    monto: 28,
  },
  {
    id: "29",
    hora: "18:10",
    tipo: "Servicio",
    descripcion: "Corte fade",
    empleado: "Carlos",
    pago: "Efectivo",
    monto: 30,
  },
  {
    id: "30",
    hora: "18:30",
    tipo: "Servicio",
    descripcion: "Recogido para boda",
    empleado: "Ana",
    pago: "Tarjeta",
    monto: 90,
  },
];

export const summaryStats = {
  gastos: mockTransactions
    .filter((t) => t.tipo === "Gasto")
    .reduce((sum, t) => sum + t.monto, 0),
  ventaTarjeta: mockTransactions
    .filter((t) => t.tipo !== "Gasto" && t.pago === "Tarjeta")
    .reduce((sum, t) => sum + t.monto, 0),
  ventaProductos: mockTransactions
    .filter((t) => t.tipo === "Producto")
    .reduce((sum, t) => sum + t.monto, 0),
};
